#!/usr/bin/env python

"""
=======================================
5 - Data association - clutter tutorial
=======================================
"""

# %%
# Tracking a single target in the presence of clutter and missed detections
# -------------------------------------------------------------------------
#
# Tracking is frequently complicated by the presence of detections which are not
# associated with the target of interest. These may range from sensor-generated noise to
# returns off intervening physical objects, or environmental effects. We refer to these
# collectively as *clutter* if they have only nuisance value and need to be filtered out.
#
# In this tutorial we introduce the use of data association algorithms in Stone Soup and
# demonstrate how they can mitigate confusion due to clutter. To begin with we use a
# **nearest neighbour** method, which is conceptually simple and associates a prediction and a
# detection based only on their proximity as quantified by a particular metric.
#

# %%
# Background
# ----------
# The principal difficulty in practical multi-object tracking is not usually to do with the state
# of an individual object. Rather it is to do with the fact that the potential association of
# measurement to prediction is fraught with ambiguity. To illustrate this point consider a couple
# of examples:
#
# .. image:: ../_static/20170705_2x2associationexamples.png
#   :width: 300
#   :alt: Exhaustive enumeration of associations of 2 targets to 2 measurements
#
# .. image:: ../_static/800px-20170607_associations.png
#   :width: 300
#   :alt: Number of potential associations of measurements to targets
#
# The first (left) is the full set of associations of two targets (crosses) with two
# measurements (stars). Green: measurement generated by one target only and target capable of
# generating one measurement only; Yellow: includes measurements generated by more than one target;
# Pink: includes targets generating more than one measurement. The second image (right) shows the
# number of ways of associating up to 5 targets with up to 10 measurements depending on whether you
# allow one-to-one (bottom), many-to-one (middle) or many-to-many (top). In this latter instance
# the number of potential associations *at a single time instance* tops out at :math:`10^{15}`
#
# Clearly it would be prohibitive to have to assess each of these options at each timestep. For
# this reason there exist a number of data association schemes. We'll set up a scenario and then
# proceed to introduce the nearest neighbour algorithm as a first means to address the association
# issue.

# %%
# Set up a simulation
# -------------------
# As in previous tutorials, we start with a target moving linearly in the 2D Cartesian plane.
import numpy as np
from scipy.stats import uniform
from datetime import datetime
from datetime import timedelta

from stonesoup.models.transition.linear import CombinedLinearGaussianTransitionModel, \
                                               ConstantVelocity
from stonesoup.types.groundtruth import GroundTruthPath, GroundTruthState

np.random.seed(1991)

start_time = datetime.now().replace(microsecond=0)
q_x = 0.005
q_y = 0.005
transition_model = CombinedLinearGaussianTransitionModel([ConstantVelocity(q_x),
                                                          ConstantVelocity(q_y)])
timesteps = [start_time]
truth = GroundTruthPath([GroundTruthState([0, 1, 0, 1], timestamp=timesteps[0])])

# Import the disturbance method for the transition model
from aduulm_scripts.utils.add_disturbance import disturbance_transition_model
# Disturbance configurations for ground truth generation
gt_transition_configs = {
    'noise_diff_coeff': [[q_x, q_y]],  # for transition model gt
    'disturbance_mode': ['jump'],
    'parameters': [[[1000, 8.0], [1200, 0.125]]]
}
process_noise_coeff_memory = [[], []]

num_steps = 1300
for k in range(1, num_steps):
    timesteps.append(start_time+timedelta(seconds=k))

    # Disturb the transition model based on the disturbance modes
    transition_model = disturbance_transition_model(transition_model, gt_transition_configs, k)
    # Save the noise coefficients (process noise memory)
    for i, model in enumerate(transition_model.model_list):
        # Collect covariance matrices for each model component
        process_noise_coeff_memory[i].append(model.noise_diff_coeff)

    truth.append(GroundTruthState(
        transition_model.function(truth[k-1], noise=True, time_interval=timedelta(seconds=1)),
        timestamp=timesteps[k]))

# %%
# Probability of detection
# ^^^^^^^^^^^^^^^^^^^^^^^^
# For the first time we introduce the possibility that, at any time-step, our sensor receives no
# detection from the target (i.e. :math:`p_d < 1`).
prob_det = 0.9

# %%
# Simulate clutter
# ^^^^^^^^^^^^^^^^
# Next generate some measurements and, since :math:`p_{fa} > 0`, add in some clutter
# at each time-step. We use the :class:`~.TrueDetection` and :class:`~.Clutter` subclasses of
# :class:`~.Detection` to help with identifying data types in plots later. A fixed number of
# clutter points are generated and uniformly distributed across
# a :math:`\pm 20` rectangular space centred on the true position of the target.
from stonesoup.types.detection import TrueDetection
from stonesoup.types.detection import Clutter
from stonesoup.models.measurement.linear import LinearGaussian
measurement_model = LinearGaussian(
    ndim_state=4,
    mapping=(0, 2),
    noise_covar=np.array([[0.75, 0],
                          [0, 0.75]])
    )

# Import the disturbance method for the measurement model
from aduulm_scripts.utils.add_disturbance import disturbance_measurement_noise, disturbance_prob_det_and_clutter
from scipy.stats import poisson

# Disturbance configurations for measurement generation
gt_measurement_noise_configs = {
    'disturbance_mode': ['jump'],
    'parameters': [[[100, 2], [300, 0.5]]]
}
gt_prob_det_configs = {
    'init_prob_det': prob_det,
    'disturbance_mode': ['jump'],
    'parameters': [[[700, 0.6667], [900, 1.5]]]
}
gt_clutter_configs = {
    'init_exp_num_clutter': 4,
    'disturbance_mode': ['jump'],
    'parameters': [[[400, 2], [600, 0.5]]]
}
exp_num_clutter = gt_clutter_configs['init_exp_num_clutter']

fov_x = fov_y = 20
fov_v_x = fov_v_y = 10
fov = [fov_x, fov_v_x, fov_y, fov_v_y]

meas_std_dev_memory = []
prob_det_memory = []
exp_num_clutter_memory = []

all_measurements = []
for k, state in enumerate(truth):
    # Disturb the measurement model based on the disturbance modes
    measurement_model = disturbance_measurement_noise(measurement_model, gt_measurement_noise_configs, k)
    # Disturb the detection probability
    prob_det = disturbance_prob_det_and_clutter(gt_prob_det_configs, k, prob_det)

    measurement_set = set()
    # Generate actual detection from the state with a 1-p_d chance that no detection is received.
    if np.random.rand() <= prob_det:
        measurement = measurement_model.function(state, noise=True)
        measurement_set.add(TrueDetection(state_vector=measurement,
                                          groundtruth_path=truth,
                                          timestamp=state.timestamp,
                                          measurement_model=measurement_model))

    # Disturb the clutter rate
    exp_num_clutter = disturbance_prob_det_and_clutter(gt_clutter_configs, k, exp_num_clutter)
    # typically number of clutter measurements is Poisson distributed
    # with the expected number of clutter per time step
    clutter_range = poisson.rvs(exp_num_clutter)

    # Generate clutter at this time-step
    truth_x = state.state_vector[0]
    truth_y = state.state_vector[2]
    for _ in range(clutter_range):
        x = uniform.rvs(truth_x - fov_x/2, fov_x)
        y = uniform.rvs(truth_y - fov_y/2, fov_y)
        measurement_set.add(Clutter(np.array([[x], [y]]), timestamp=state.timestamp,
                                    measurement_model=measurement_model))

    meas_std_dev_memory.append(np.sqrt(measurement_model.noise_covar))
    prob_det_memory.append(prob_det)
    exp_num_clutter_memory.append(exp_num_clutter)

    all_measurements.append(measurement_set)

# %%
# Plot the ground truth and measurements with clutter.

# Plot ground truth.
from stonesoup.plotter import AnimatedPlotterly
plotter = AnimatedPlotterly(timesteps, tail_length=0.3)
plotter.plot_ground_truths(truth, [0, 2])

# Plot true detections and clutter.
plotter.plot_measurements(all_measurements, [0, 2])
plotter.fig

# %%
# Distance Hypothesiser and Nearest Neighbour
# -------------------------------------------
#
# Perhaps the simplest way to associate a detection with a prediction is to measure a 'distance'
# to each detection and hypothesise that the detection with the lowest distance
# is correctly associated with that prediction.
#
# An appropriate distance metric for states described by Gaussian distributions is the
# *Mahalanobis distance*. This quantifies the distance of a point relative to a given
# distribution.
# In the case of a point :math:`\mathbf{x} = [x_{1}, ..., x_{N}]^T`, and distribution with mean
# :math:`\boldsymbol{\mu} = [\mu_{1}, ..., \mu_{N}]^T` and covariance matrix :math:`P`, the
# Mahalanobis distance of :math:`\mathbf{x}` from the distribution is given by:
#
# .. math::
#       \sqrt{(\mathbf{x} - \boldsymbol{\mu})^T P^{-1} (\mathbf{x} - \boldsymbol{\mu})}
#
# which equates to the multi-dimensional measure of how many standard deviations a point is away
# from the mean.
#

# %%
# We're going to create a hypothesiser that ranks detections against predicted measurement
# according to the Mahalanobis distance, where those that fall outside of :math:`3` standard
# deviations of the predicted measurement's mean are ignored. To do this we create a
# :class:`~.DistanceHypothesiser` which pairs incoming detections with track predictions, and pass
# it a :class:`Measure` class which (in this instance) calculates the Mahalanobis distance.
#
# The hypothesiser must use a predicted state given by the predictor, create a measurement
# prediction using the updater, and compare this to a detection given a specific metric. Hence, it
# takes the predictor, updater, measure (metric) and missed distance (gate) as its arguments. We
# therefore need to create a predictor and updater, and to initialise a measure.
from stonesoup.predictor.kalman import KalmanPredictor
predictor = KalmanPredictor(transition_model)
from stonesoup.updater.kalman import KalmanUpdater
updater = KalmanUpdater(measurement_model)

# %%
# Construct a Self-Assessor for the Single-Object Tracking in Clutter
# Using Nearest Neighbour Association
# ^^^^^^^^^^^^^^^^^^^^^^^^^
#
# We're now ready to construct a self-assessor to monitor the assumptions of the tracking algorithm.

from stonesoup.selfassessor.sot_clutter_selfassessor import SOTClutterSelfAssessor
from scipy.special import gammaincinv

# Self-assessor settings
sa_settings = {
    "num_X": 7,
    "n_st": {"innovation": 35, "detection": 10, "gate": 35,
             "clutter": 15,
             "combined": 10, "threshold": 10,
             "binomial_clutter": 10, "binomial_combined_innovation": 10
             },
    "n_c": {"innovation": 1, "detection": 1, "gate": 1,
             "clutter": 1,
             "combined": 1, "threshold": 1,
             "binomial_clutter": 1, "binomial_combined_innovation": 1
             },
    "dim_meas": measurement_model.ndim_meas,
    "alpha_threshold_dc": {"innovation": 0.1, "detection": 0.3, "gate": 0.1,
                           "clutter": 0.2,
                           "combined": 0.3, "threshold": 0.3,
                           "binomial_clutter": 0.3, "binomial_combined_innovation": 0.3
                           },
    "sigma_cutoff_alpha": 0.01,
    "trust_discount": {"innovation": 0.99, "detection": 0.99, "gate": 0.99,
                       "clutter": 0.99,
                       "combined": 0.99, "threshold": 0.99,
                       "binomial_clutter": 0.99, "binomial_combined_innovation": 0.99
                       }
}
selfassessor = SOTClutterSelfAssessor(num_X=sa_settings["num_X"],
                                      n_st=sa_settings["n_st"],
                                      n_c=sa_settings["n_c"],
                                      prob_detect=gt_prob_det_configs['init_prob_det'],
                                      dim_meas=sa_settings["dim_meas"],
                                      alpha_threshold_dc=sa_settings["alpha_threshold_dc"],
                                      sigma_cutoff=np.sqrt(2 * gammaincinv(sa_settings["dim_meas"] / 2,
                                                                           1 - sa_settings["sigma_cutoff_alpha"])),
                                      trust_discount=sa_settings["trust_discount"],
                                      exp_clutter=gt_clutter_configs["init_exp_num_clutter"],
                                      fov_area=fov_x*fov_y,
                                      association_algorithm="nn")
selfassessor_measures_combined_history = []
multiple_selfassessor_measures_history = {
    'detection': [],
    'clutter': []
}

from stonesoup.selfassessor.nis import NIS
# NIS settings
nis_settings = {
    "window_length": 1,  # window size of the NIS averaging
    "alpha": 0.01,  # significance level
    "dim_meas": measurement_model.ndim_meas,
    "sigma_cutoff_alpha": 0.0001  # gating significance level
}
sigma_cutoff_gating = np.sqrt(2 * gammaincinv(nis_settings["dim_meas"] / 2, 1 - nis_settings["sigma_cutoff_alpha"]))
nis = NIS(window_length=nis_settings["window_length"],
          alpha=nis_settings["alpha"],
          dim=nis_settings["dim_meas"],
          sigma_cutoff=sigma_cutoff_gating,
          probability_detected=gt_prob_det_configs["init_prob_det"],
          clutter_exp_number=gt_clutter_configs["init_exp_num_clutter"],
          fov=fov,
          association_algorithm="nn")
nis_measures_history = []

# %%
from stonesoup.hypothesiser.distance import DistanceHypothesiser
from stonesoup.measures import Mahalanobis
# Note: Self-assessment results depend on the DistanceHypothesiser settings,
# so ensure they match the self-assessment configuration.
hypothesiser = DistanceHypothesiser(predictor, updater, measure=Mahalanobis(), missed_distance=sigma_cutoff_gating)

# %%
# Now we use the :class:`~.NearestNeighbour` data associator, which picks the hypothesis pair
# (predicted measurement and detection) with the highest 'score' (in this instance, those that are
# closest to each other).
#
# .. image:: ../_static/NN_Association_Diagram.png
#   :width: 500
#   :alt: Image showing NN association for one track
#
# In the diagram above, there are three possible detections to be considered for association (some
# of which may be clutter). The detection with a score of :math:`0.4` is selected by the nearest
# neighbour algorithm.

from stonesoup.dataassociator.neighbour import NearestNeighbour
data_associator = NearestNeighbour(hypothesiser)

# %%
# Run the Kalman filter with the associator
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# With these components, we can run the simulated data and clutter through the Kalman filter.

# Create prior
from stonesoup.types.state import GaussianState
prior = GaussianState([[0], [1], [0], [1]], np.diag([1.5, 0.5, 1.5, 0.5]), timestamp=start_time)

# %%
# Loop through the predict, hypothesise, associate and update steps.

from stonesoup.types.track import Track

track = Track([prior])
for n, measurements in enumerate(all_measurements):
    hypotheses = data_associator.associate([track],
                                           measurements,
                                           start_time + timedelta(seconds=n))
    hypothesis = hypotheses[track]

    if hypothesis.measurement:
        post = updater.update(hypothesis)
        # save nearest neighbour associated measurement for self-assessment
        nn_associated_meas = hypothesis.measurement.state_vector
        z_p = hypothesis.measurement_prediction.mean
        S_p = hypothesis.measurement_prediction.covar
    else:  # When data associator says no detections are good enough, we'll keep the prediction
        post = hypothesis.prediction
        # used for self-assessment
        nn_associated_meas = None
        H = measurement_model.matrix()
        z_p = np.dot(H, hypothesis.prediction.mean)
        S_p = np.dot(np.dot(H, hypothesis.prediction.covar), np.transpose(H)) + measurement_model.noise_covar

    track.append(post)

    # self-assessment
    num_meas = len(measurements)
    selfassessor.assess(z_p, S_p, nn_associated_meas, num_meas)
    nis_measures = nis.assess(z_p, S_p, nn_associated_meas)
    # save self-assessment results for plotting
    selfassessor_measures_combined = selfassessor.get_sas_measures(index_or_key='combined')
    selfassessor_measures_combined_history.append(selfassessor_measures_combined)
    nis_measures_history.append(nis_measures)
    # SA components
    selfassessor_measures_detection = selfassessor.get_sas_measures(index_or_key='detection')
    multiple_selfassessor_measures_history['detection'].append(selfassessor_measures_detection)
    selfassessor_measures_clutter = selfassessor.get_sas_measures(index_or_key='clutter')
    multiple_selfassessor_measures_history['clutter'].append(selfassessor_measures_clutter)

# %%
# Plot the resulting track

plotter.plot_tracks(track, [0, 2], uncertainty=True)
plotter.fig.show(renderer="browser")
plotter.show()

# %%
# Plot the self-assessment measures
from aduulm_scripts.utils.plotting import plot_selfassessment_with_nis, plot_multiple_selfassessment_measures
plot_selfassessment_with_nis(selfassessor_measures_combined_history, nis_measures_history, nis_settings["alpha"],
                             opinion_type='Combined Opinion', assessor_type='NNSelfAssessor')
plot_multiple_selfassessment_measures(multiple_selfassessor_measures_history, assessor_type='NNSelfAssessor')

# %%
# Ground-truth based evaluation
from aduulm_scripts.utils.plotting import plot_gospa
from stonesoup.metricgenerator.ospametric import GOSPAMetric
from stonesoup.measures import Euclidean
measure = Euclidean([0, 2])
gospa_generator = GOSPAMetric(c=20, p=1, measure=measure)
gospa_values = gospa_generator.compute_over_time(track[1:], [0] * len(track),
                                                 truth[:-1], [0] * len(truth))
plot_gospa(gospa_values)

# %%
# If you experiment with the clutter and detection parameters, you'll notice that there are often
# instances where the estimate drifts away from the ground truth path. This is known as *track
# seduction*, and is a common feature of 'greedy' methods of association such as the nearest
# neighbour algorithm.

# %%
# Self-assessment references
# ----------
# .. [#] T. Griebel, J. Mueller, M. Buchholz, and K. Dietmayer, “Kalman filter meets subjective logic:
#        A self-assessing Kalman filter using subjective logic,” in 2020 IEEE 23rd International
#        Conference on Information Fusion (FUSION). IEEE, 2020.
# .. [#] T. Griebel, J. Mueller, P. Geisler, C. Hermann, M. Herrmann, M. Buchholz, and K. Dietmayer,
#        “Self-assessment for single-object tracking in clutter using subjective logic,”
#        in 2022 25th International Conference on Information Fusion (FUSION). IEEE, 2022.
# .. [#] T. Griebel, J. Heinzler, M. Buchholz and K. Dietmayer, "Online Performance Assessment
#        of Multi-Sensor Kalman Filters Based on Subjective Logic," 2023 26th International
#        Conference on Information Fusion (FUSION), Charleston, SC, USA, 2023, pp. 1-8.

# sphinx_gallery_thumbnail_path = '_static/sphinx_gallery/Tutorial_5.PNG'
